title: 'slinkinone.github.io'
description: "Slinkin Technologies"
baseurl: ""
url: "https://slinkinone.github.io"

header_pages:
  - index.md
  - about.md
  - contact.md

#style: light # dark (default), light, hacker, or nord

footer: 'Slinkin Technologies 2020-2026: <a href="https://slinkin.tech/">website</a>, <a href="mailto:info@slinkin.tech">email</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
