title: "slinkin-tech"
description: "Slinkin Technologies"
baseurl: ""
url: "https://slinkinone.github.io"

#

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

logo: assets/img/favicon.png
#

header_pages:
  - index.md
  - dc_engine.md
  - blog.md
  - about.md
  - portal.md

#

style: light # dark (default), light, hacker, or nord
#listen_for_clients_preferred_style: true
disable_google_fonts: true

#
tracking: true
csp:
  default-src: "'none'"
  connect-src: "'self' https://mc.yandex.ru"
  base-uri: "'self'"
  form-action: "'none'"
  img-src: "'self' https: data: https://mc.yandex.ru"
  style-src: "'self' 'unsafe-inline' https://fonts.googleapis.com"
  font-src: "'self' https://fonts.gstatic.com data:"
  media-src: "'self'"
  object-src: "'none'"
  child-src: "'self'"
  script-src: "'self' 'unsafe-inline' https://mc.yandex.ru"

#
footer: 'Â© 2020-2026 slinkin-tech: <a href="https://slinkin.tech/">website</a>, <a href="mailto:info@slinkin.tech">email</a>, <a href="/privacy-policy">privacy-policy</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console