title: 'slinkinone.github.io'
description: "Slinkin Technologies"
baseurl: ""
url: "https://slinkinone.github.io"

#

plugins:
  - jekyll-seo-tag

logo: assets/img/favicon.png
#

header_pages:
  - index.md
  - dc_engine.md
  - blog.md
  - about.md
  - portal.md

#

style: light # dark (default), light, hacker, or nord
#listen_for_clients_preferred_style: true
disable_google_fonts: true

footer: 'Slinkin Technologies 2020-2026: <a href="https://slinkin.tech/">website</a>, <a href="mailto:info@slinkin.tech">email</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
